[package]
name = "beacon-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
alacritty_terminal.workspace = true
beacon-columns.workspace = true
beacon-kube.workspace = true
gpui-kit.workspace = true
nucleo-matcher.workspace = true
anyhow.workspace = true
futures.workspace = true
serde_json.workspace = true
serde-saphyr.workspace = true
tokio.workspace = true
tracing.workspace = true
