[package]
name = "beacon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "A cross-platform Kubernetes client built with Rust and GPUI"

[[bin]]
name = "beacon"
path = "src/main.rs"

[dependencies]
beacon-kube.workspace = true
beacon-ui.workspace = true
gpui-kit.workspace = true
anyhow.workspace = true
directories.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
